sudo: required
services:
  - docker

before_install:
  - chmod +x ./model_download.sh
  - docker build -t quarkus7/fico-vs-kiska .

script:
  - docker run quarkus7/fico-vs-kiska python test.py

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quarkus7/which-tram
  - docker tag quarkus7/which-tram registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web

# deploy:
#   provider: heroku
#   app: fico-alebo-kiska
#   api_key:
#     secure: "$HEROKU_KEY"
