sudo: required
services:
  - docker

before_install:
  - docker build -t quarkus7/fico-vs-kiska .

script:
  - docker run quarkus7/fico-vs-kiska python test.py

deploy:
  provider: heroku
  app: fico-alebo-kiska
  api_key:
    secure: "$HEROKU_KEY"
